"""
event.py — SynthEvent: the atomic unit of composition.

Every note, strike, cluster, noise burst is a SynthEvent. Events are
generated by Composition.generate(), then rendered to audio by Renderer.
The parameters dict is the "100 knobs" — any synthesis param can go here.
"""

from dataclasses import dataclass, field
from typing import Optional


@dataclass
class SynthEvent:
    """One musical event — a note, bell strike, noise burst, etc."""

    time: float                     # Start time in seconds
    pitch_class: int                # 0-11 (C=0, C#=1, ..., B=11)
    octave: int                     # Octave number (2-6 typical)
    duration: float                 # Duration in seconds
    amplitude: float                # Linear amplitude (0.0-1.0)
    instrument: str                 # Key into InstrumentRegistry
    category: str = ""              # Grouping label (e.g. "melody", "boy", "papa")
    section: str = ""               # Section name (e.g. "storm", "calm")
    parameters: dict = field(default_factory=dict)  # The 100 knobs

    def to_dict(self):
        """Serialize to JSON-compatible dict. All values native Python types."""
        return {
            'time': float(self.time),
            'pc': int(self.pitch_class),
            'octave': int(self.octave),
            'duration': float(self.duration),
            'amplitude': float(self.amplitude),
            'type': str(self.instrument),
            'category': str(self.category),
            'section': str(self.section),
            **{k: _clean(v) for k, v in self.parameters.items()}
        }

    @classmethod
    def from_dict(cls, d):
        """Deserialize from dict."""
        return cls(
            time=d['time'],
            pitch_class=d.get('pc', d.get('pitch_class', 0)),
            octave=d['octave'],
            duration=d['duration'],
            amplitude=d['amplitude'],
            instrument=d.get('type', d.get('instrument', '')),
            category=d.get('category', ''),
            section=d.get('section', ''),
            parameters={k: v for k, v in d.items()
                       if k not in ('time', 'pc', 'pitch_class', 'octave',
                                    'duration', 'amplitude', 'type',
                                    'instrument', 'category', 'section')},
        )


def _clean(v):
    """Convert numpy types to native Python for JSON serialization."""
    import numpy as np
    if isinstance(v, (np.integer,)):
        return int(v)
    if isinstance(v, (np.floating,)):
        return float(v)
    if isinstance(v, np.ndarray):
        return v.tolist()
    return v
